<?php

namespace MainBundle\Repository;

/**
 * AutoBusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Symfony\Component\HttpFoundation\RequestStack;

class AutoBusRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByCurrentCompagnie($idCompagnie)             // utiliser dans Formulaire Parcours
    {
        // Pour le Formulaire Parcours

        $qb=$this->createQueryBuilder('auto_bus');

        if(! is_null($idCompagnie))
        {
            $qb->where('auto_bus.compagnie= :idCompagnie')
                ->setParameter('idCompagnie',$idCompagnie);
        }

        return $qb;
    }
}
