<?php

namespace MainBundle\Repository;

/**
 * CompagnieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompagnieRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFind()
    {
        $qb=$this->createQueryBuilder('comp')
            ->addOrderBy('comp.nomComp','ASC');

        return $qb->getQuery()->getResult();
    }

    public function getNbreCompagnie()
    {
        $qb=$this->createQueryBuilder('compagnie')
            ->select('count(compagnie.id)');

        return $qb->getQuery()->getSingleScalarResult();
    }
}
