<?php

namespace MainBundle\Repository;

/**
 * OptionAchatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionAchatRepository extends \Doctrine\ORM\EntityRepository
{
}
