<?php

namespace MainBundle\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCurrentUser()
    {
        $qb=$this->createQueryBuilder('ticket');

        if (! is_null($_SESSION['idUser']))
        {
            $qb->where('ticket.user= :idUser')
            ->setParameter('idUser', $_SESSION['idUser']);
        }

        return $qb->getQuery()->getResult();
    }

    public function getNbreTicketVenduByCurrentUser()
    {
        $qb=$this->createQueryBuilder('ticket');

        if (! is_null($_SESSION['idUser']))
        {
            $qb->where('ticket.user= :idUser')
                ->setParameter('idUser', $_SESSION['idUser']);
        }

        $qb->select('count(ticket.id)');

        return $qb->getQuery()->getSingleScalarResult();
    }


}
