<?php

namespace MainBundle\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCurrentUser($idUser)
    {
        $qb=$this->createQueryBuilder('ticket');

        if (! is_null($idUser))
        {
            $qb->where('ticket.user= :idUser')
            ->setParameter('idUser', $idUser);
        }

        return $qb->getQuery()->getResult();
    }

    public function getNbreTicketVenduByCurrentUser($idUser)
    {
        $qb=$this->createQueryBuilder('ticket');

        if (! is_null($idUser))
        {
            $qb->where('ticket.user= :idUser')
                ->setParameter('idUser', $idUser);
        }

        $qb->select('count(ticket.id)');

        return $qb->getQuery()->getSingleScalarResult();
    }


}
