<?php

namespace MainBundle\Repository;

/**
 * TrajetGareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrajetGareRepository extends \Doctrine\ORM\EntityRepository
{
}
