<?php

namespace MainBundle\Repository;

use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * TrajetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrajetRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByCompagnie($idCompagnie)
    {
        $qb=$this->createQueryBuilder('trajet');

        if (! is_null($idCompagnie))
        {
            $qb->where('trajet.compagnie= :idCompagnie')
                ->setParameter('idCompagnie', $idCompagnie);
        }


        return $qb->getQuery()->getResult();
    }


    public function findTrajetsParents()                // Utiliser dans Trajet Type
    {
        $qb=$this->createQueryBuilder('trajet')
                ->where('trajet.trajetParent is null');

        return $qb;
    }

    public function findByCurrentCompagnie()             // utiliser dans Formulaire Parcours
    {
        // Pour le Formulaire Parcours

        $qb=$this->createQueryBuilder('trajet');

        $idCompagnie=$_SESSION['idCompagnie'];

        if(! is_null($idCompagnie))
        {
            $qb->where('trajet.compagnie= :idCompagnie')
                ->setParameter('idCompagnie',$idCompagnie);
        }


        return $qb;
    }


    public function getNbreTrajetByCurrentCompagnie()
    {
        $qb=$this->createQueryBuilder('trajet');

        if (! is_null($_SESSION['idCompagnie']))
        {
            $qb->andWhere('trajet.compagnie= :idCompagnie')
                ->setParameter('idCompagnie', $_SESSION['idCompagnie']);
        }

        $qb->select('count(trajet.id)');
        ;

        return $qb->getQuery()->getSingleScalarResult();
    }
}
