<?php

namespace MainBundle\Repository;

/**
 * VoyageTrajetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoyageTrajetRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCustomVoyage($idCompagnie,$idGareDepart,$idGareArrivee,$dateVoyage)
    {
        $qb=$this->createQueryBuilder('voyageTrajet')
            ->join('voyageTrajet.trajet','trajet')
            ->join('voyageTrajet.voyage','voyage')
            ->where('voyageTrajet.nbrePlaceRestant > :seuil')
            ->andWhere('voyage.statusVoyage= :statusVoyage')
            ->setParameter('seuil', 0)
            ->setParameter('statusVoyage', 'open');


        if(! (empty($dateVoyage) or $dateVoyage == null))
        {

            $qb->andWhere('voyage.dateVoyage >= :dateVoyage')
                ->setParameter('dateVoyage',$dateVoyage);
        }

        if(! (empty($idCompagnie) or $idCompagnie == null))
        {

            $qb->andWhere('trajet.compagnie= :idCompagnie')
                ->setParameter('idCompagnie', $idCompagnie);
        }

        if(! (empty($idGareDepart) or $idGareDepart == null))
        {
            $qb->andWhere('trajet.source= :idGareDepart')
                ->setParameter('idGareDepart',$idGareDepart);
        }

        if(! (empty($idGareArrivee) or $idGareArrivee== null))
        {
            $qb->andWhere('trajet.destination= :idGareArrivee')
                ->setParameter('idGareArrivee',$idGareArrivee);
        }

        return $qb->getQuery()->getResult();
    }
}
