<?php

namespace MainBundle\Repository;

/**
 * VoyageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoyageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCompagnie($idCompagnie)
    {
        $qb=$this->createQueryBuilder('voyage')
            ->join('voyage.autoBus','autoBus')
            ->where('autoBus.compagnie= :idCompagnie')
            ->setParameter('idCompagnie', $idCompagnie);

        return $qb->getQuery()->getResult();
    }

    public function findVoyageByStatus($status, $idCompagnie=null)
    {
        $qb=$this->createQueryBuilder('voyage')
            ->where('voyage.statusVoyage= :status')
            ->setParameter('status', $status);

        if (! is_null($idCompagnie))
        {
            $qb->join('voyage.autoBus', 'autoBus')
                ->andWhere('autoBus.compagnie= :idCompagnie')
                ->setParameter('idCompagnie', $idCompagnie);
        }

        return $qb->getQuery()->getResult();
    }


    public function findCustomVoyage($idCompagnie,$idGareDepart,$idGareArrivee,$dateVoyage)
    {
        $qb=$this->createQueryBuilder('voyage')
                 ->join('voyage.trajet','trajet')
            ->where('voyage.dateVoyage >= :dateVoyage')
            ->setParameter('dateVoyage',$dateVoyage);


        if(! (empty($idCompagnie) || $idCompagnie === null))
        {

            $qb->andWhere('trajet.compagnie= :idCompagnie')
                ->setParameter('idCompagnie', $idCompagnie);
        }

        if(! (empty($idGareDepart) || $idGareDepart === null))
        {
            $qb->andWhere('trajet.gareDepart= :idGareDepart')
            ->setParameter('idGareDepart',$idGareDepart);
        }

        if(! (empty($idGareArrivee) || $idGareArrivee=== null))
        {
            $qb->andWhere('trajet.destination= :idGareArrivee')
            ->setParameter('idGareArrivee',$idGareArrivee);
        }

        return $qb->getQuery()->getResult();
    }

    public function getNbreVoyageByCompagnieAndStatus($idCompagnie,$status)
    {
        $qb=$this->createQueryBuilder('voyage')
                ->join('voyage.autoBus', 'autoBus')
                ->where('voyage.statusVoyage= :status')
                ->setParameter('status', $status);

        if (! is_null($idCompagnie))
        {
            $qb->andWhere('autoBus.compagnie= :idCompagnie')
                ->setParameter('idCompagnie', $idCompagnie);
        }

        $qb->select('count(voyage.id)');
            ;

        return $qb->getQuery()->getSingleScalarResult();
    }
}
